### ISSUE TITLE
Investigate how to properly handle in-app engine's tests

### ISSUE THREAD

**Issue by st0012** [Shopify/ruby-lsp-rails#221]
Assume an user has a Rails app called `my_app`, which has in-app engines with the following file structure:

```
my_app
├── app
├── config
├── (other Rails app folders)
└── engines
    └── my_engine
        └── test/my_test.rb
```

### Todos

- [ ] Check what's the official/best practice of running an in-app engine's unit tests
    - The [Rails engine guide](https://guides.rubyonrails.org/engines.html#testing-an-engine) doesn't cover much about writing/running tests.
- [ ] When opening `my_test.rb` from the `my_app` workspace, the code lens should have generate such command:
    
    ```
    bundle exec bin/rails test engines/my_engine/test/my_test.rb
    ```
    
    We need to check if this are expected to work or not.
    - If the answer is no, it means tests are expected to be executed under the `my_engine` directory.
- [ ] Is there any other common in-app Rails engine setup we should consider
