### ISSUE TITLE
Add methods generated through metaprogramming to the index

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp-rails#403]
I make occasional use of `delegate` in my code, which is rails specific: https://api.rubyonrails.org/classes/Module.html#method-i-delegate

Are addons able to contribute to the index? I don't think this addon currently does that. From the code in `ruby-lsp`, `DeclarationListener.on_call_node_enter` seems like the place where it handles buildin things like that.

Perhaps addons should to be able to hook into `index_single` to register a dispatcher of their own and contribute to the index?

```[tasklist]
### Tasks
- [ ] delegate
- [ ] has_many
- [ ] has_one
- [ ] belongs_to
- [ ] scope
- [ ] enum
- [ ] has_one_attached
- [ ] has_many_attached
- [ ] has_secure_token
- [ ] attribute
```

**Comment by Earlopain** [comment]
Looking forward to that. Rails provides some methods where this would be very useful (like enum declarations) and with the index continuosly getting better the cases where it doesn't work start to feel weird (this is a compliment 😄)

**Comment by vinistock** [comment]
Yeah, definitely! The idea is that addons will have the ability to bake the logic for configurations style DSLs, improving the knowledge in the index.

A good example is association methods. When we find a `belongs_to :user`, we know which methods have to be inserted in the index.

**Comment by andyw8** [comment]
@vinistock are you thinking this would be a new kind of `Entry`, e.g. `Entry::DynamicMethod` ?

**Comment by vinistock** [comment]
Ideally not because then everything else should work by default (resolution, completion candidates, etc). Do you see a reason for having a separate entry for it?

**Comment by andyw8** [comment]
Add-ons can now contribute to the index: https://shopify.github.io/ruby-lsp/add-ons.html#enhancing-features
